docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - v2:
      - "Quick Start": v2/quick-start.md
      - "Rendering Views":
          - "The PhpRenderer": v2/php-renderer.md
          - "View Scripts": v2/view-scripts.md
          - "The ViewEvent": v2/view-event.md
      - Helpers:
          - Introduction: v2/helpers/intro.md
          - Asset: v2/helpers/asset.md
          - BasePath: v2/helpers/base-path.md
          - Cycle: v2/helpers/cycle.md
          - Doctype: v2/helpers/doctype.md
          - Escape: v2/helpers/escape.md
          - Gravatar: v2/helpers/gravatar.md
          - HeadLink: v2/helpers/head-link.md
          - HeadMeta: v2/helpers/head-meta.md
          - HeadScript: v2/helpers/head-script.md
          - HeadStyle: v2/helpers/head-style.md
          - HeadTitle: v2/helpers/head-title.md
          - HtmlAttributes: v2/helpers/html-attributes.md
          - HtmlList: v2/helpers/html-list.md
          - HtmlObject: v2/helpers/html-object.md
          - HtmlTag: v2/helpers/html-tag.md
          - Identity: v2/helpers/identity.md
          - InlineScript: v2/helpers/inline-script.md
          - Json: v2/helpers/json.md
          - Layout: v2/helpers/layout.md
          - Partial: v2/helpers/partial.md
          - Placeholder: v2/helpers/placeholder.md
          - Url: v2/helpers/url.md
          - "Advanced usage of helpers": v2/helpers/advanced-usage.md
      - 'Application Integration':
          - 'Stand-Alone': v2/application-integration/stand-alone.md
      - Cookbook:
          - "Setting module-specific Layouts": v2/cookbook/setting-module-specific-layouts.md
      - Migration:
          - "Preparing for Version 3": v2/migration/preparing-for-v3.md
site_name: laminas-view
site_description: 'Flexible view layer supporting and providing multiple view layers, helpers, and more.'
repo_url: 'https://github.com/laminas/laminas-view'
extra:
  project: Components
  current_version: v2
  versions:
    - v2

plugins:
  - redirects:
      redirect_maps:
        quick-start.md: v2/quick-start.md
        php-renderer.md: v2/php-renderer.md
        view-scripts.md: v2/view-scripts.md
        view-event.md: v2/view-event.md
        helpers/intro.md: v2/helpers/intro.md
        helpers/asset.md: v2/helpers/asset.md
        helpers/base-path.md: v2/helpers/base-path.md
        helpers/cycle.md: v2/helpers/cycle.md
        helpers/doctype.md: v2/helpers/doctype.md
        helpers/escape.md: v2/helpers/escape.md
        helpers/flash-messenger.md: v2/helpers/flash-messenger.md
        helpers/gravatar.md: v2/helpers/gravatar.md
        helpers/head-link.md: v2/helpers/head-link.md
        helpers/head-meta.md: v2/helpers/head-meta.md
        helpers/head-script.md: v2/helpers/head-script.md
        helpers/head-style.md: v2/helpers/head-style.md
        helpers/head-title.md: v2/helpers/head-title.md
        helpers/html-attributes.md: v2/helpers/html-attributes.md
        helpers/html-list.md: v2/helpers/html-list.md
        helpers/html-object.md: v2/helpers/html-object.md
        helpers/html-tag.md: v2/helpers/html-tag.md
        helpers/identity.md: v2/helpers/identity.md
        helpers/inline-script.md: v2/helpers/inline-script.md
        helpers/json.md: v2/helpers/json.md
        helpers/layout.md: v2/helpers/layout.md
        helpers/partial.md: v2/helpers/partial.md
        helpers/placeholder.md: v2/helpers/placeholder.md
        helpers/url.md: v2/helpers/url.md
        helpers/advanced-usage.md: v2/helpers/advanced-usage.md
        application-integration/stand-alone.md: v2/application-integration/stand-alone.md
        cookbook/setting-module-specific-layouts.md: v2/cookbook/setting-module-specific-layouts.md
